In [1]:
import pyodbc
import pandas as pd
import numpy as np
from Google import create_service

In [2]:
##conexi√≥n a BD
DRIVER_NAME ='SQL SERVER'
SERVER_NAME = 'iloca'
DATABASE_NAME = 'UNYSOFT'
UID='consultailoca'
PWD='2018iloca'; 

try:
    conn = pyodbc.connect('DRIVER='+DRIVER_NAME+';SERVER='+SERVER_NAME+';DATABASE='+DATABASE_NAME+';ENCRYPT=no;UID='+UID+';PWD='+ PWD +'')
    print('Connection created') 
except pyodbc.DatabaseError as e:
    print('Database Error 1:')
    print(str(e.value[1]))
except pyodbc.Error as e:
    print('Connection Error 2:')
    print(str(e.value[1]))

Connection created

In [3]:
cursor = conn.cursor()

In [4]:
cursor.execute("SELECT dbo.INDEPContratoCAB.CtoEmpresa, dbo.maeEmpresa.empNombre, dbo.INDEPContratoCAB.CtoCodigo, dbo.INDMaeUNegocioActivas.CtoDescripcion, cast(dbo.INDEPContratoCAB.NumeroContrato as int),dbo.INDEPContratoCAB.Descripcion, dbo.INDEPAvanceCAB.NumeroPago, dbo.INDEPContratoCAB.RutContratista, dbo.INDTrContratistas.RazonSocial, cast(dbo.INDEPAvanceCAB.NetoDocumento as int),cast(dbo.INDEPAvanceCAB.ValorImpuesto1 as int), cast(dbo.INDEPAvanceCAB.TotalTotal as int), cast(dbo.INDEPAvanceCAB.TotalaPago as int), dbo.INDEPAvanceCAB.VBdo, dbo.INDEPAvanceCAB.VBao, dbo.INDEPAvanceCAB.VBsc, dbo.INDEPAvanceCAB.VBct,dbo.INDEPAvanceCAB.FechaContable, dbo.INDEPAvanceCAB.CodDocCobro, cast(dbo.INDEPAvanceCAB.Nfactura as int), cast(dbo.INDEPAvanceCAB.RetencionEjecucionValor as int), cast(dbo.INDEPAvanceCAB.descanticipovalor as int), dbo.INDEPContratoCAB.plncodigo, dbo.INDEPAvanceCAB.AnoControl, dbo.INDEPAvanceCAB.MesControl, dbo.INDEPAvanceCAB.MovControl, dbo.INDEPAvanceCAB.oc  FROM         dbo.INDEPAvanceCAB INNER JOIN dbo.INDEPContratoCAB ON dbo.INDEPAvanceCAB.IdContrato = dbo.INDEPContratoCAB.IdContrato INNER JOIN dbo.INDTrContratistas ON dbo.INDEPContratoCAB.RutContratista = dbo.INDTrContratistas.RutContratista INNER JOIN dbo.INDMaeUNegocioActivas ON dbo.INDEPContratoCAB.CtoEmpresa = dbo.INDMaeUNegocioActivas.CtoEmpresa AND dbo.INDEPContratoCAB.CtoCodigo = dbo.INDMaeUNegocioActivas.CtoCodigo INNER JOIN dbo.maeEmpresa ON dbo.INDEPContratoCAB.CtoEmpresa = dbo.maeEmpresa.empCodigo WHERE     dbo.INDEPAvanceCAB.oc like 'AOC%' and (VBct is null or VBct ='FACTAX' ) and dbo.INDEPAvanceCAB.AnoControl=('2023') and dbo.INDEPAvanceCAB.MesControl=('1') and dbo.INDEPAvanceCAB.MovControl=('1')")

In [5]:
data=cursor.fetchall()
data_EEPP=pd.DataFrame(np.array(data))

In [6]:
data_EEPP

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,004,CONSTRUCTORA INDEPENDENCIA SPA,2205100000,CONSTITUCION PARQUE DEL SOL 79 VIV (DS19),316,IDF,1,76797009-9,VELECTRIC SPA,571771,...,None,FAVT,629,34306,0,111001111,2023,1,1,AOC-067857
1,004,CONSTRUCTORA INDEPENDENCIA SPA,2205100000,CONSTITUCION PARQUE DEL SOL 79 VIV (DS19),317,PINTURAS,2,77618353-9,VALLES DEL MAULE SPA,1532019,...,None,FAVT,21,91921,0,111001111,2023,1,1,AOC-068047
2,004,CONSTRUCTORA INDEPENDENCIA SPA,2205100000,CONSTITUCION PARQUE DEL SOL 79 VIV (DS19),189,SC PENSION CONTRATISTAS,12,9012492-7,ROSA PARRA GONZALEZ,10001,...,None,FAVT,164,0,0,111001211,2023,1,1,AOC-068078
3,004,CONSTRUCTORA INDEPENDENCIA SPA,2205100000,CONSTITUCION PARQUE DEL SOL 79 VIV (DS19),280,ADICIONAL TRABAJOS EXTERIORES,12,16725910-3,MARCOS MAURICIO FAUNDEZ CONTRERAS,665000,...,None,FAVT,547,39900,0,111001111,2023,1,1,AOC-067789
4,004,CONSTRUCTORA INDEPENDENCIA SPA,2202200000,CURICO DON SEBASTIAN DE RAUQUEN VII 119 VIV (D...,421,CTO POST VENTAS,1,17794995-7,SEBASTIAN ANTONIO LUCERO OLIVOS,1560000,...,None,FAVT,282,93600,0,111001111,2023,1,1,AOC-067807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,003,CONSTRUCTORA COLBUN SPA,22CMOPS040,MOLINA PARQUE DEL SOL 173 VIV (94 VIV),10,CTO ENFIERRADURA CAMARA AP,1,7233029-3,EUFRACIO DIONOR DIAZ PARDO,385000,...,None,FAVT,525,23100,0,111001111,2023,1,1,AOC-067944
988,003,CONSTRUCTORA COLBUN SPA,22CMOPS040,MOLINA PARQUE DEL SOL 173 VIV (94 VIV),12,CTO IDF,1,15130459-1,MARILIN DE LAS MERCEDES NAVARRO MARTINEZ,980600,...,None,FAVT,965,58836,0,111030031,2023,1,1,AOC-068003
989,003,CONSTRUCTORA COLBUN SPA,PVTA000180,PVTA PROYECTOS TALCA VALLES DEL COUNTRY,127,SC POST VENTA CARPINTERIA LUALMEN 16-12-2022,1,77404806-5,LUALMEN SPA,630000,...,None,FAVT,12,37800,0,111001111,2023,1,1,AOC-066297
990,003,CONSTRUCTORA COLBUN SPA,PPV2000000,PV-TALCA PARQUE DEL SOL 83 VIV.,78,SC.MO POSTVENTA PINTURA Y OTROS,3,15139825-1,CRISTIAN MANUEL RAMIREZ MERA,335000,...,None,FAVT,9,20100,0,111050053,2023,1,1,AOC-067337
991,003,CONSTRUCTORA COLBUN SPA,PPV2000000,PV-TALCA PARQUE DEL SOL 83 VIV.,68,POSTVENTA GASFITERIA OOVV,14,16003801-2,ISMAEL AYALA HUARNEZ,440000,...,None,FAVT,421,26400,0,111050053,2023,1,1,AOC-067378

In [7]:
"""
Getting  Google Sheets
"""
CLIENT_SECRET_FILE = 'client_secret.json'
API_NAME = 'sheets'
API_VERSION = 'v4'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

service = create_service(CLIENT_SECRET_FILE, API_NAME, API_VERSION,SCOPES )

google_sheets_id = '15konHY_RcXRBl_oEePTnzmusoRAUSm5OHGq-HXTfDf0'

sheets v4 service created successfully

In [8]:
def construct_request_body(value_array, dimension: str='ROWS') -> dict:
    try:
        request_body = {
            'majorDimension': dimension,
            'values': value_array
        }
        return request_body
    except Exception as e:
        print(e)
        return {}

response = service.spreadsheets().values().get(
    spreadsheetId=google_sheets_id,
    majorDimension='ROWS',
    range='BD_EEPP_REGULAR!A2:AA'
    ).execute()

In [9]:
    recordset = data_EEPP.values.tolist()
    """
    Insert column names
    """
    request_body_columns = construct_request_body([])
    service.spreadsheets().values().update(
        spreadsheetId=google_sheets_id,
        valueInputOption='USER_ENTERED',
        range='BD_EEPP_REGULAR!A2:AA',
        body=request_body_columns
    ).execute()

    """
    Insert rows
    """
    request_body_values = construct_request_body(recordset)
    service.spreadsheets().values().update(
        spreadsheetId=google_sheets_id,
        valueInputOption='USER_ENTERED',
        range='BD_EEPP_REGULAR!A2:AA',
        body=request_body_values
    ).execute()

    print('Task is complete')

    cursor.close()

Task is complete